services:
  webserver:
    container_name: walock-webserver
    build: ./webserver
    ports:
    - "443:443"
    environment:
      ADDRESS: wallock.xyz
  web:
    container_name: wallock-web
    build: 
      context: ./web
      target: prod
  api:
    container_name: wallock-api
    build:
      context: ./api
      target: prod
    env_file: ./api/.env
