services:
  webserver:
    container_name: wallock-webserver
    build: ./webserver
    ports:
    - "3000:3000"
    environment:
      ADDRESS: http://localhost:3000
    develop:
      watch:
        - action: sync
          path: ./webserver/
          target: /app/
  web:
    container_name: wallock-web
    build: 
      context: ./web
      target: dev
    develop:
      watch:
        - action: sync
          path: ./web/
          target: /app/
          ignore:
          - node_modules/
        - action: rebuild
          path: ./web/package.json
  api:
    container_name: wallock-api
    build: ./api
    develop:
      watch:
        - action: rebuild
          path: ./api/
